# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  # ====================================================================================================================
  # = MESSAGES
  # ====================================================================================================================
  messages:
    cache-duration: 1

  # ====================================================================================================================
  # = THYMELEAF
  # ====================================================================================================================
  thymeleaf:
    cache: false

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  level:
    com:
      gitlab:
        computerhuis:
          dco: DEBUG
