#  https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  jmx:
    enabled: false
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 1s

  # ====================================================================================================================
  # = DATA SOURCE
  # ====================================================================================================================
  datasource:
    hikari:
      poolName: hikari-pool-dco

  # ====================================================================================================================
  # = JPA
  # ====================================================================================================================
  jpa:
    open-in-view: false
    properties:
      hbm2ddl:
        auto: validate

      # ================================================================================================================
      # = HIBERNATE
      # ================================================================================================================
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        jdbc:
          time_zone: Europe/Amsterdam
          use_get_generated_keys: true
          lob:
            non_contextual_creation: true

  # ====================================================================================================================
  # = WEB
  # ====================================================================================================================
  web:
    locale: nl

  # ====================================================================================================================
  # = THYMELEAF
  # ====================================================================================================================
  thymeleaf:
    prefix: classpath:/view

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  pattern:
    console: '%date [%highlight(%-5level)][%cyan(%logger:%line)] -%mdc{RID} %message%n'
  level:
    root: INFO
    com:
      gitlab:
        computerhuis:
          dco: DEBUG
    org:
      springframework:
        security:
          web:
            csrf: DEBUG
